# Generated by Django 4.2.1 on 2023-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='inventaire',
            field=models.TextField(blank=True),
        ),
    ]
