# Generated by Django 4.2.1 on 2023-05-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0002_alter_station_inventaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='inventaire',
        ),
        migrations.AlterField(
            model_name='substation',
            name='inventaire',
            field=models.TextField(blank=True),
        ),
    ]
