# Generated by Django 4.2.1 on 2023-05-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0003_remove_station_inventaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='inventaire',
            field=models.TextField(blank=True),
        ),
    ]
