# Generated by Django 4.2.1 on 2023-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0004_station_inventaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='inventaire',
        ),
    ]
